// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4vvpNo-mLkmTVPo9ohBRY4BtfmJ-Fsjs',
    appId: '1:744547259978:web:6632d9afc66725ce1878b3',
    messagingSenderId: '744547259978',
    projectId: 'login-8d6b7',
    authDomain: 'login-8d6b7.firebaseapp.com',
    storageBucket: 'login-8d6b7.appspot.com',
    measurementId: 'G-FG8YVG4LGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDayf7PDFxSygDeasT9rqDZB3JRGtVCPx8',
    appId: '1:744547259978:android:426af9b009c9f4881878b3',
    messagingSenderId: '744547259978',
    projectId: 'login-8d6b7',
    storageBucket: 'login-8d6b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3i-T5q2cjNuHZBdafD9QQ2HX5ZI7EsVs',
    appId: '1:744547259978:ios:04debc91c3d389d61878b3',
    messagingSenderId: '744547259978',
    projectId: 'login-8d6b7',
    storageBucket: 'login-8d6b7.appspot.com',
    iosBundleId: 'com.example.chap22',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3i-T5q2cjNuHZBdafD9QQ2HX5ZI7EsVs',
    appId: '1:744547259978:ios:04debc91c3d389d61878b3',
    messagingSenderId: '744547259978',
    projectId: 'login-8d6b7',
    storageBucket: 'login-8d6b7.appspot.com',
    iosBundleId: 'com.example.chap22',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4vvpNo-mLkmTVPo9ohBRY4BtfmJ-Fsjs',
    appId: '1:744547259978:web:593928707eef93fb1878b3',
    messagingSenderId: '744547259978',
    projectId: 'login-8d6b7',
    authDomain: 'login-8d6b7.firebaseapp.com',
    storageBucket: 'login-8d6b7.appspot.com',
    measurementId: 'G-34RH5K0EL3',
  );

}